{{
  config(
    materialized = 'incremental',
    unique_key = 'alert_hk',
    incremental_strategy = 'append',
    schema = 'raw_vault'
  )
}}

/*
  hub_alert — hub for threshold-breach alert events.

  Business key: alert_id (UUID generated by the alert generator).
  Alerts are sparse compared to readings — only generated when a reading
  breaches a clinical threshold.
*/

select
    {{ dbt_utils.generate_surrogate_key(['alert_id']) }}  as alert_hk,
    alert_id                                               as alert_id_bk,
    load_datetime,
    record_source

from {{ ref('stg_alerts') }}

{% if is_incremental() %}
where load_datetime > (select max(load_datetime) from {{ this }})
{% endif %}
