{{
  config(
    materialized = 'incremental',
    unique_key = 'reading_hk',
    incremental_strategy = 'append',
    schema = 'raw_vault'
  )
}}

/*
  hub_reading — hub for individual measurement events.

  Business key: reading_id (UUID generated by the wearable simulator).
  One row per distinct reading. This is a high-volume hub, growing by
  ~500-1000 rows per patient per day.
*/

select
    {{ dbt_utils.generate_surrogate_key(['reading_id']) }}  as reading_hk,
    reading_id                                               as reading_id_bk,
    load_datetime,
    record_source

from {{ ref('stg_readings') }}

{% if is_incremental() %}
where load_datetime > (select max(load_datetime) from {{ this }})
{% endif %}
