{{
  config(
    materialized = 'incremental',
    unique_key = ['reading_hk', 'load_datetime'],
    incremental_strategy = 'append',
    schema = 'raw_vault'
  )
}}

/*
  sat_reading_context — contextual information about a reading.

  Separated from sat_reading_value because context (activity, location) may
  not be available for every reading and changes at a different conceptual grain
  from the measurement value itself.

  mood_score is nullable — self-reported, not generated by the simulator,
  included for future extensibility.
*/

select
    {{ dbt_utils.generate_surrogate_key(['reading_id']) }}          as reading_hk,
    load_datetime,
    {{ dbt_utils.generate_surrogate_key([
        'activity_type',
        'location_type'
    ]) }}                                                             as hash_diff,
    measured_at                                                       as effective_from,
    record_source,
    activity_type,
    location_type,
    cast(null as integer)                                             as mood_score

from {{ ref('stg_readings') }}

where activity_type is not null
   or location_type is not null

{% if is_incremental() %}
  and load_datetime > (select max(load_datetime) from {{ this }})
{% endif %}
